.model flat, c
.code
extern GetFileVersionInfoA_Original:DWORD
extern GetFileVersionInfoByHandle_Original:DWORD
extern GetFileVersionInfoExA_Original:DWORD
extern GetFileVersionInfoExW_Original:DWORD
extern GetFileVersionInfoSizeA_Original:DWORD
extern GetFileVersionInfoSizeExA_Original:DWORD
extern GetFileVersionInfoSizeExW_Original:DWORD
extern GetFileVersionInfoSizeW_Original:DWORD
extern GetFileVersionInfoW_Original:DWORD
extern VerFindFileA_Original:DWORD
extern VerFindFileW_Original:DWORD
extern VerInstallFileA_Original:DWORD
extern VerInstallFileW_Original:DWORD
extern VerLanguageNameA_Original:DWORD
extern VerLanguageNameW_Original:DWORD
extern VerQueryValueA_Original:DWORD
extern VerQueryValueW_Original:DWORD
GetFileVersionInfoA_ML proc
  jmp DWORD ptr GetFileVersionInfoA_Original
GetFileVersionInfoA_ML endp
GetFileVersionInfoByHandle_ML proc
  jmp DWORD ptr GetFileVersionInfoByHandle_Original
GetFileVersionInfoByHandle_ML endp
GetFileVersionInfoExA_ML proc
  jmp DWORD ptr GetFileVersionInfoExA_Original
GetFileVersionInfoExA_ML endp
GetFileVersionInfoExW_ML proc
  jmp DWORD ptr GetFileVersionInfoExW_Original
GetFileVersionInfoExW_ML endp
GetFileVersionInfoSizeA_ML proc
  jmp DWORD ptr GetFileVersionInfoSizeA_Original
GetFileVersionInfoSizeA_ML endp
GetFileVersionInfoSizeExA_ML proc
  jmp DWORD ptr GetFileVersionInfoSizeExA_Original
GetFileVersionInfoSizeExA_ML endp
GetFileVersionInfoSizeExW_ML proc
  jmp DWORD ptr GetFileVersionInfoSizeExW_Original
GetFileVersionInfoSizeExW_ML endp
GetFileVersionInfoSizeW_ML proc
  jmp DWORD ptr GetFileVersionInfoSizeW_Original
GetFileVersionInfoSizeW_ML endp
GetFileVersionInfoW_ML proc
  jmp DWORD ptr GetFileVersionInfoW_Original
GetFileVersionInfoW_ML endp
VerFindFileA_ML proc
  jmp DWORD ptr VerFindFileA_Original
VerFindFileA_ML endp
VerFindFileW_ML proc
  jmp DWORD ptr VerFindFileW_Original
VerFindFileW_ML endp
VerInstallFileA_ML proc
  jmp DWORD ptr VerInstallFileA_Original
VerInstallFileA_ML endp
VerInstallFileW_ML proc
  jmp DWORD ptr VerInstallFileW_Original
VerInstallFileW_ML endp
VerLanguageNameA_ML proc
  jmp DWORD ptr VerLanguageNameA_Original
VerLanguageNameA_ML endp
VerLanguageNameW_ML proc
  jmp DWORD ptr VerLanguageNameW_Original
VerLanguageNameW_ML endp
VerQueryValueA_ML proc
  jmp DWORD ptr VerQueryValueA_Original
VerQueryValueA_ML endp
VerQueryValueW_ML proc
  jmp DWORD ptr VerQueryValueW_Original
VerQueryValueW_ML endp
end
